name: Frontend Security Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  frontend-security:
    runs-on: ubuntu-latest
    name: Run Frontend Security Scans

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- ESLint Setup ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm install

      # --- Run ESLint & Save HTML Report ---
      - name: Run ESLint and Save HTML Report
        run: |
          npm install --save-dev eslint@8 eslint-plugin-security
          npx eslint . --ext .js,.ts -f html -o eslint-report.html || true

      # --- Semgrep Scan & Report ---
      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep and Save Report
        run: |
          semgrep scan --config=auto . --json > semgrep-report.json || true

      # --- Organize Reports into a Folder ---
      - name: Organize Reports
        run: |
          mkdir -p security-reports
          mv eslint-report.html security-reports/
          mv semgrep-report.json security-reports/

      # --- Upload All Reports as "frontend-report" ---
      - name: Upload Frontend Security Report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-report
          path: security-reports
